### ISSUE TITLE
Failed to use developer dashboard for editting app info 

### ISSUE THREAD

**Issue by lbj96347** [altizure/sdk.examples#2]
## Behaviour

When I try to update my app info (the app domain for oauth callback), I failed. I saw the submit button blinking but it doesn't work. Sometimes it may notify me: please upload an photo for avatar. But there is an avatar online already.

## How to reproduce 

1. Create a new application;
2. Try to update app domain of other info. 
3. Check the console in Safari or Chrome, there are couple of 403 error code.

**Comment by idezzzz** [comment]
Please check whether `modheader` is turned off.
