### ISSUE TITLE
How to hide the Yellow wireframe,"objMarker.bboxColor = 0xff0000" not worked 

### ISSUE THREAD

**Issue by cn17173** [altizure/sdk.examples#3]
How to hide the Yellow wireframe,"objMarker.bboxColor = 0xff0000" not worked

**Comment by jingbogit** [comment]
objMarker.dim() will hide it.
ps. objMarker.dim() will show it.
it's similar to the blue square fence for AltizureProjectMarker.

**Comment by cn17173** [comment]
It works. Thanks a lot!
