### ISSUE TITLE
Obj can't show texture

### ISSUE THREAD

**Issue by BryceQing** [altizure/sdk.examples#4]
Hello,I loaded an obj file which contains mtl and textures from my folder,but it can't show textures.Can you help me check the code 
`
let obj2 = new altizure.OBJMarker({
        position: {
          lng: 113.93916035952945,
          lat: 22.536167496052556,
          alt: 30.976462667429363
        },
        sandbox: sandbox,
        name: 'arbor',
        shape: 'CUSTOMIZE',
        objUrl: './Simple_Module/Moon/Moon 2K.obj',
        mtlUrl: './Simple_Module/Moon/Moon 2k.mtl',
        
        upDir: {x: 0,y: 1,z: 0},
        "scale": 1
      })
`
and mtl contains the map_Kd files name

**Comment by jingbogit** [comment]
usually it is caused by obj not having correct material name in mtl, or mtl not having the correct path to texture.

plz send your obj/mtl/jpg in a zip folder, to jingbo(at)altizure.com

we'll have a look.

**Comment by jingbogit** [comment]
file name should not contain space, special characters.

issue resolved.
