### ISSUE TITLE
the earth map quality not work.

### ISSUE THREAD

**Issue by cn17173** [altizure/sdk.examples#5]
let options = {
        altizureApi:{
          key: '7MkQf8UggsPaadvrlKALspJWZejZAJOLHn3cnIy'
        },
        camera: {
          flyTo: { alt:1020.0739295752213,
            lat:22.538388886344876,
            lng:113.94255600866971,
            north:-27.271585092584015,
            tilt:74.7023627906978 }
        },
        renderItems: {
          earth: true,
          earthUseTexture: true,
          featureInView: false,
          orbitRing: true,
          **quality: 2 // [1, 100], default 60, 100 for best quality.** 
        }
      }

**Comment by jingbogit** [comment]
quality controls the 3D models of AltizureProjectMarker.

whats you expected behaviour? and whats the current behaviour?

**Comment by cn17173** [comment]
I want to improve the quality of earth maps.Is there any way?

**Comment by jingbogit** [comment]
> I want to improve the quality of earth maps.Is there any way?

Unfortunately it is not possible at the moment. I'll label this issue as a `feature request`. We'll try to provide an interface to do that in the coming month.

**Comment by jingbogit** [comment]
In SDK V3, quality will be able to control the earth map details.

If you read Chinese, you may check:
https://github.com/altizure/sdk.examples/blob/master/QaA/upgrade-v3.md
